language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
script:
  - python3 -m bin.mutual_friends --format csv  kreed58 maxkorzh_official
  - python3 -m bin.mutual_friends --format json kreed58 maxkorzh_official

  - python3 -m bin.show_status egor.tensin

  - ./.travis/track_status.sh
  - ./.travis/online_sessions.sh
