name: Test

on:
  push:
  pull_request:
  schedule:
    # Weekly, at 6:45 AM on Thursday (somewhat randomly chosen).
    - cron: '45 6 * * 4'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_NO_PYTHON_VERSION_WARNING: 1

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.4, 3.5, 3.6, 3.7, 3.8, 3.9]

    name: 'Python ${{ matrix.python-version }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install dependencies
        run: |
          pip install -r constraints.txt
          pip install -r requirements.txt

      - name: Run the tests
        run: ./.ci/bin/main.sh
