name: Test

on:
  push:
  pull_request:
  schedule:
    # Weekly, at 6:45 AM on Thursday (somewhat randomly chosen).
    - cron: '45 6 * * 4'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
    name: 'Python ${{ matrix.python-version }}'
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_NO_PYTHON_VERSION_WARNING: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the tests
        run: ./.ci/bin/main.sh

  publish_pypi:
    needs: [test]
    runs-on: ubuntu-18.04
    name: Publish
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_NO_PYTHON_VERSION_WARNING: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install tools
        run: python3 -m pip install --upgrade build
      - name: Build package
        run: python3 -m build
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          if-no-files-found: error
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: '${{ secrets.PYPI_API_TOKEN }}'
